language: python
python:
  - 3.6

sudo: false

os:
  - linux


services:
  - docker

env:
  global:
  - CONDA_DEPS="pytest numpy trimesh pyglet"
  - PYTHONPATH="$HOME/underactuated:/opt/drake/lib/python3.6/site-packages"
  matrix:
  - DRAKE_URL="https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-bionic.tar.gz"

install:
  - python docker_build.py --drake_url=$DRAKE_URL

script:
  - python docker_run.py -e /pydrake_kuka/run_tests.sh
